version: '3.8'

services:
  order_service:
    image: order_service:order-server
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile.yml
    command: bash -c "python manage.py runserver 0.0.0.0:9000"


