# Generated by Django 3.1.7 on 2021-03-21 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210313_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 2, 44, 41, 706898, tzinfo=utc)),
        ),
    ]
