# Generated by Django 3.1.7 on 2021-03-21 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210321_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 2, 54, 47, 632831, tzinfo=utc)),
        ),
    ]
