# Generated by Django 3.1.7 on 2021-03-27 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210321_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 10, 22, 57, 663261, tzinfo=utc)),
        ),
    ]
