# Generated by Django 3.1.7 on 2021-03-28 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210327_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 9, 25, 35, 187392, tzinfo=utc)),
        ),
    ]
